---
title: ""
---

<br> 

### 2018


* _Jeff_: [Data science in (bio)stats departments (ASA Chairs)](https://docs.google.com/presentation/d/1Hayp7JQH7uy_X-GOq5vPoAR9Ver0xRJS5PrVqWb87u4/edit?usp=sharing)
* _Jeff_: [Studying Human Gene Expression at Population Scale with the Recount Project (UCSD 2018)](https://docs.google.com/presentation/d/1eixophYVMrNM479mDrCm24wRKiCNh0Xi2T6FhaNX1lQ/edit?usp=sharing)
* _Jeff_: [Improving the value of public genomic data with phenotype prediction (SAGES 2018)](https://docs.google.com/presentation/d/1iX1iNGvqqW2sWJd1a5BPEMCV1Z-cRd4Q_XIVSfWICoM/edit?usp=sharing)
* _Jeff_: [Defining and implementing reproducibility and replicability (SCT2018)](https://docs.google.com/presentation/d/1lLgk7BEo65xSHldRoaX26zao7I2cJcXKyZIJxtNq27o/edit?usp=sharing)
* _Jeff_: [The future of data science is plain text (eCOTs)](https://docs.google.com/presentation/d/13d_Pn3aOFjm0Rze9qo9K_8ZIwt4n9Hqv3yec-XAaRMI/edit?usp=sharing)
* _Jeff_: [Predicting and using metadata (Yale)](https://docs.google.com/presentation/d/1QKDIGUKrO8tZkR355_Bg5MGA4fUvr3AdICPlXXg8XoI/edit?usp=sharing)
* _Jeff_: [Predicting and using metadata (Toronto)](https://docs.google.com/presentation/d/1FgUZZU6pW91J7zH0OqrEgxfnV1Py_ZGL3ZKHfbOZskY/edit?usp=sharing)
* _Jeff_: [Human behaviorial challenges in biomedical data science](https://docs.google.com/presentation/d/1uFxTgBXe55OmU55V_uV-AawCH3eiIkHP_Y00Kzyj0jg/edit?usp=sharing)
* _Jeff_: [Human-data interaction (Washington)](https://docs.google.com/presentation/d/1nVAw7E-snu_bcCNhSlUuCP6eWYMxNBDJvsS_Ak4k0D0/edit?usp=sharing)
* _Jeff_: [Is most published research really false? (Columbia)](https://docs.google.com/presentation/d/1S9VXkcMLZZ405rMQOaIz1OyNw-43Kt5hER4wcUS1H6M/edit?usp=sharing)

### 2017


* _Jeff_: [The data science problem is humans and the solution is the internet](https://docs.google.com/presentation/d/1f2Kzwh0ObGo7TACIzCIa5GsI3UqF8Eez11RT3TdwypU/edit?usp=sharing)
* _Jeff_: [Building a human gene expression resource (New York Genome Center)](https://docs.google.com/presentation/d/1_fNKQAHe3_ALBVUyRIZ83sRIsdq9O6ygnPTyrRvRXQI/edit?usp=sharing)
* _Jeff_: [Is most published research false? (McGill)](https://docs.google.com/presentation/d/1hzdSDaPPSE9xUYZHhOVfQIRPPdwe0A9SdE7QDsK3bOA/edit?usp=sharing) 
* _Jeff_: [Coming to terms with data overload in science](https://docs.google.com/presentation/d/1diGUr8oHmJByBJy9eEvLBh3qIpUIjjy1P2TxasAWSHo/edit?usp=sharing), [pdf](https://github.com/jtleek/jtleek.github.io/files/1185814/jsm2017.pdf)
* _Jeff_: [What can we (& you) learn about RNA from 70,000 (human) samples? (UCLA)](https://docs.google.com/presentation/d/1OGOVApkE72TqCWV0aMOfiwLzzZWoH8ZCprOWs8Pz1R0/edit?usp=sharing)
* _Jeff_: [What can we (& you) learn about RNA from 70,000 (human) samples? (OHSU)](https://docs.google.com/presentation/d/1rAXyjdIvRBkRw93DinMUhfj9vs9yqfcEBctD4jO-Xgo/edit?usp=sharing)
* _Jeff_: [What can we (& you) learn about RNA from 70,000 (human) samples?](https://docs.google.com/presentation/d/1mjMF1yDGgLQW4JNgiKO7XBY7I7j2laTq1kGYo3Q1rYw/edit?usp=sharing)
* _Jeff_: [Data Science as a Science](https://docs.google.com/presentation/d/1qf4_78ArLmL6MWwchLm1HPMBft5jJfdEhpTk2UPecHo/edit?usp=sharing)
* _Jeff_: [What can we learn about RNA from 70,000 (human) samples?](https://docs.google.com/presentation/d/1GBdWeHU5HI6Fqy9NDe_6RL2oDl5HjJdsmCHSBlAk0m4/edit?usp=sharing)
* _Jeff_: [Is most published research really false?](https://docs.google.com/presentation/d/12SAKwzNs97DjcwTvIUi5husTf3EFlX_pfyxCKRjictE/edit?usp=sharing)

### 2016

* _Jeff_: [Re-annotating the human transcriptome with recount](https://docs.google.com/presentation/d/1XCLfuCD1A0ODczmg4oKK5E3n-dwh6ohHjCYSj_doqbU/edit?usp=sharing)
* _Jeff_: [Is the p-value really the problem?](https://docs.google.com/presentation/d/1nbaKvANCZkN8hbrd31R25WIfQszWFjGyiGeRaqHO1pI/edit?usp=sharing)
* _Jeff_: [Data science as a science](http://www.slideshare.net/jtleek/data-science-as-a-science)


### 2015

* _Jeff_: [JHU Data Science MOOCs - behind the scenes](http://www.slideshare.net/jtleek/jhu-data-science-moocs-behind-the-scenes)
* _Jeff_: [Fixing the leaks in the pipeline from public genomics data to the clinic](http://www.slideshare.net/jtleek/fixing-the-leaks-in-the-pipeline-from-public-genomics-data-to-the-clinic)
* _Jeff_: [Evidence based data analysis (NAS workshop on statistical reproducibility)](http://www.slideshare.net/jtleek/evidence-based-data-analysis)
* _Jeff_: [We are all statisticians now (Rome Science Festival)](http://www.slideshare.net/jtleek/leek-romesf2015)
* _Alyssa_: [High-resolution gene expression analysis (PhD thesis defense)](https://speakerdeck.com/alyssafrazee/high-resolution-gene-expression-analysis)
* _Leo_: [Dissecting human brain development at high resolution using RNA-seq (ENAR 2015)](http://www.slideshare.net/lcolladotor/dissecting-human-brain-development-at-high-resolution-using-rnaseq)


### 2014


* _Jeff_: [We are all statisticians now](https://speakerdeck.com/jtleek/we-are-all-statisticians-now)
* _Jeff_: [Big data and reproducibility](https://speakerdeck.com/jtleek/big-data-and-reproducibility/)
* _Alyssa_: [Adventures in Computational Biology](https://speakerdeck.com/alyssafrazee/adventures-in-computational-biology)
* _Jeff_: [Data science education at JHSPH](http://www.slideshare.net/jtleek/education-37613273)
* _Jeff_: [Statisticians and big data](http://www.slideshare.net/jtleek/big-data-and-statisticians)
* _Alyssa_: [Engineering new tools for differential expression analysis](https://speakerdeck.com/alyssafrazee/differential-expression-analysis-tools)
* _Jeff_: [10 things statistics taught us about big data](http://www.slideshare.net/jtleek/10-things-statistics-taught-us-about-big-data)
* _Jeff_: [Genomics at JHU Biostats](http://www.slideshare.net/jtleek/flash-talk-about-johns-hopkins-genomics)
* _Jeff_: [The world's largest data science program: The Johns Hopkins Data Science Specialization](http://www.slideshare.net/jtleek/the-largest-data-science-program-in-the-world-the-johns-hopkins-data-science-specialization)

### Old

* _Jeff_: [JHU Job Talk (2009)](http://www.slideshare.net/jtleek/jhu-feb2009)