---
title: ""
---

</br> </br>

### For current students at Johns Hopkins

If you are a current Hopkins student and are interested in working with me come by my office any time the door is open and I'll be happy to talk about open projects. 

I am always excited to talk to students about new projects, it is the [best part of the job](http://simplystatistics.org/2012/10/26/i-love-those-first-discussions-about-a-new-research/)
. I will be extra pumped to talk to you if:

1. You know something about our [projects](./projects.html) 
2. Double that if you have used my [software and data](./codedata.html)
3. Triple that if you issued a pull request to any of our software online. 
4. Quadruple that if you come with your own idea related to anything I work on

If our projects don't seem that interesting to you, I'm also happy to help introduce you to other folks in data science or genomics who might have projects you are more interested in. 

### For prospective students at Johns Hopkins

I mostly supervise students from [Biostatistics](http://www.jhsph.edu/departments/biostatistics/), but am also excited to work with students in any department at JHU. I am not on the admissions committee so I pretty much don't have any say over whether you will get admitted. But if you want to do a Ph.D. at Hopkins Biostat and you: (1) have the serious math chops to get through our program (it is at the top end of rigor among Biostat programs) and (2) have written a cool R package and put it on Github or done an awesome data analysis and posted it on the web, then I want to hear from you. Send me an email to my gmail account with your CV attached, a link to your project, and a one liner about the coolest research project you can think of that relates to anything me or any of my colleagues do. I'll make sure the right people see your application. 

### For prospective postdocs

I am always looking for awesome potential postdocs. There are some positions that I have funded to tackle specific ideas related to our projects. But if you have an interesting idea you'd like to take on, I can probably figure out a way to scrounge up the money to pay for it if you can sell me on it :). 

Here are the minimum things I look for in a postdoc:

* Written at least 2 first author papers 
* Written at least 1 open source software package
* [Problem forward philosophy](http://simplystatistics.org/2013/05/29/what-statistics-should-do-about-big-data-problem-forward-not-solution-backward/)
* Has read about our [projects](./projects.html), used our [software and data](./codedata.html), or fixed our [software](./codedata.html)
* Has at least one idea they want to work on unrelated to their dissertation

If you are interested in doing a postdoc send me an email with your CV, a link to the software package you built, and a short (one paragraph) description of a research project you have imagined working on. 

If you are a grad student who is interested in applying for postdoctoral funding through NSF, NIH, or another funding source and want to work with me, send me an email with the above information and I'll be happy to help you with your application. 



