name: postcards-build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  site-builder:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - run: Rscript -e 'install.packages("postcards", dependencies = TRUE)'
      - run: Rscript -e 'rmarkdown::render("index.Rmd")'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: postcards website updated
